[package]
name = "roguelike"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "game"
path = "src/bin.rs"

[dependencies]
colored = "2.1.0"
roguelike-core = { path = "../core" }